server:
  port: 9602
spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}
      database: "work_slack_bot"
---
spring:
  config:
    activate:
      on-profile: test
  mongodb:
    embedded:
      version: 4.0.21